version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - my-mysql:/var/lib/mysql:rw
    ports:
      - ${DB_PORT}:${DB_PORT}
#    networks:
#      - default

  web:
    image: openjdk:15-jdk
    command: java -jar ./build/libs/my-application.jar
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
    working_dir: /var/www
    volumes:
      - ./:/var/www:ro
    environment:
      JAVA_OTPS: " -server -Xms4g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication "
      DB_HOST: db #override env
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
#    networks:
#      - default

volumes:
  my-mysql:
#
#networks:
#  default:
#    external:
#      name: gateway
